kind: pipeline
type: docker
name: default

steps:
  - name: test
    image: maven:3.8.6-eclipse-temurin-17-alpine
    commands:
      - export LOGGING_LEVEL="info"
      - mvn clean test

trigger:
  event:
    - push
